### ISSUE TITLE
Detailed documentation about flavor

### ISSUE THREAD

**Issue by brizaldi** [VNAPNIC/Flutter_Architecture#3]
Hi, is there any article or documentation about how to implements flavor for iOS? And suppose i have different API Key (ex: google maps API key we have to put it inside manifest), any idea where to put it so that i can have different value for each flavor build?

**Comment by VNAPNIC** [comment]
u can config IP server here
https://github.com/VNAPNIC/Flutter_Architecture/blob/master/lib/config/src/build_config.dart

**Comment by VNAPNIC** [comment]
The project has config flavor for iOS

**Comment by brizaldi** [comment]
Found a really good article about this problem: [https://www.chwe.at/2020/10/flutter-flavors/](https://www.chwe.at/2020/10/flutter-flavors/)

closing this issue.
